<?php
$dbUsername="4z56GwqMWq";
$dbPassword="Tua6kNkv5u";
$hostName="remotemysql.com";
$dbName="4z56GwqMWq";
$dbPort=3306;
$con=mysqli_connect($hostName,$dbUsername,$dbPassword,$dbName);
if(!$con)
{
die("Eroare de conexiune");
$string="Neconectat";
echo("<script>console.log('".$string."');</script>");
}
else
{
$string="Conectat";
echo("<script>console.log('".$string."');</script>");
}
?>
